exports.quotes = [

    "Absence makes the heart grow fonder",
    "Actions speak louder than words",
    "All for one and one for all",
    "All's fair in love and war",
    "All work and no play makes Jack a dull boy", 
    "All's well that ends well",
    "An apple a day keeps the doctor away",
    "An apple never falls far from the tree",
    "An ounce of prevention is worth a pound of cure",
    "Appearances can be deceiving",
    "April showers bring May flowers",
    "Bad news travels fast",
    "Beauty is in the eye of the beholder",
    "Beauty is only skin deep",
    "Beggars can't be choosers",
    "Behind every good man is a good woman",
    "The best defense is a good offense",
    "The best laid plans of mice and men (often go astray)",
    "Better late than never",
    "Better safe than sorry",
    "Better to have loved and lost than never to have loved at all",
    "Beware of Greeks bearing gifts",
    "The bigger thet are the harder they fall",
    "A bird in the hand is worth two in the bush",
    "Birds of a feather flock together",
    "Blood is thicker than water",
    "Boys will be boys",
    "Caught between a rock and a hard place",
    "A chain is only a strong as its weakest link",
    "Charity begins at home",
    "The chickens have come home to roost",
    "Cleanliness is next to godliness",
    "Close, but no cigar",
    "Cold hands, warm heart",
    "The cure is worse than the disease",
    "Curiosity killed the cat",
    "The customer is always right",
    "Damned if you do, damned if you don't",
    "Discretion is the better part of valor",
    "Do unto others as you would have them do unto you",
    "A dog is a man's best friend"

]